[workspace]
authors = ["Steven Eisinger <steven.a.eisinger@gmail.com>"]
channels = ["conda-forge"]
name = "monumental-interview"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
clean = "rm -rf $PIXI_PROJECT_ROOT/build"
build = "bash $PIXI_PROJECT_ROOT/build.sh"
start = "bash $PIXI_PROJECT_ROOT/run.sh"
format = "clang-format -i -- $PIXI_PROJECT_ROOT/src/*.cpp $PIXI_PROJECT_ROOT/src/*.h || shfmt --write -i 4 -d $PIXI_PROJECT_ROOT"

[dependencies]
websocketpp = ">=0.8.2,<0.9"
qt6-main = ">=6.9.1,<7"
cmake = ">=3.28,<3.30"
go-shfmt = ">=3.11.0,<4"
gcc_linux-64 = ">=15.1.0,<16"
gxx_linux-64 = ">=15.1.0,<16"
boost = ">=1.82.0,<2"
glib = ">=2.84.2,<3"
clang-format = ">=20.1.7,<21"
nlohmann_json = ">=3.12.0,<4"
